/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StrcLoaderButton {
        /**
          * True if the button is disabled.
         */
        "disabled": boolean;
        /**
          * True gives feedback that something is loading.
         */
        "loading": boolean;
        /**
          * The label displayed when loading.
         */
        "loadingLabel": string;
        /**
          * The button's type.
         */
        "type": string;
    }
}
declare global {
    interface HTMLStrcLoaderButtonElement extends Components.StrcLoaderButton, HTMLStencilElement {
    }
    var HTMLStrcLoaderButtonElement: {
        prototype: HTMLStrcLoaderButtonElement;
        new (): HTMLStrcLoaderButtonElement;
    };
    interface HTMLElementTagNameMap {
        "strc-loader-button": HTMLStrcLoaderButtonElement;
    }
}
declare namespace LocalJSX {
    interface StrcLoaderButton {
        /**
          * True if the button is disabled.
         */
        "disabled"?: boolean;
        /**
          * True gives feedback that something is loading.
         */
        "loading"?: boolean;
        /**
          * The label displayed when loading.
         */
        "loadingLabel"?: string;
        /**
          * The button's type.
         */
        "type"?: string;
    }
    interface IntrinsicElements {
        "strc-loader-button": StrcLoaderButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "strc-loader-button": LocalJSX.StrcLoaderButton & JSXBase.HTMLAttributes<HTMLStrcLoaderButtonElement>;
        }
    }
}
